/**
 * MacroSignal
 * -----------
 * The core data shape for a single AI-generated trading signal.
 * This is what Gemini returns for each open Bayse market, and what
 * every card/chart component expects as its `signal` prop.
 */
export interface MacroSignal {
  /** A unique, punchy headline generated by AI for THIS SPECIFIC SELECTION */
  headline: string;

  /** The broad event topic from Bayse (e.g. "Nigeria Inflation") */
  eventTitle: string;

  /** The specific selection title from Bayse (e.g. "Will it exceed 20%?") */
  marketTitle: string;

  /** compatibility alias for marketTitle */
  market_question: string;

  /** AI's probability for this specific selection */
  probability: number;

  /** AI's reasoning for this specific selection */
  logic: string;

  /** Sentiment for this specific selection */
  sentiment: "BULLISH" | "BEARISH" | "RISK_ALERT" | "NEUTRAL";

  /** Pre-computed reliability scores */
  source_reliability: number;
  historical_accuracy: number;

  /** Bayse IDs */
  eventId: string;
  marketId: string;

  /** Current market price (YES probability) */
  yesProbability: number;

  /** Recommended direction */
  direction: "BUY_YES" | "BUY_NO" | "WAIT";

  /** Market category */
  category?: string;

  /** Historical probability trend */
  trend?: number[];
}
